### ISSUE TITLE
Create a design document for the use of hybrid keys for ML-KEM

### ISSUE THREAD

**Issue by nhorman** [openssl/project#1022]
we've discussed what hybrid keys should look like in terms of data structures.  We need to document that design before we implement it

**Comment by baentsch** [comment]
What's the difference to openssl/private#661?

**Comment by baentsch** [comment]
How does such design document look like, @nhorman ? Would it need more than wording like follows:

- Extending the code in https://github.com/openssl/openssl/pull/25640 a key manager and KEM logic shall be developed that
  - can maintain two generic EVP_PKEY structures, incl. public and private key material, e.g., generating two keys instead of one when requested, responding to all key management operations triggering corresponding actions on both objects; the reported security strength should be the minimum of the two constituent security strengths; the returned encoded public key shall be the concatenation of the constituent encoded public keys
  - operate these two EVP_PKEYs as a single KEM in the following way: Do two KEM encap/decap operations instead of one, encapsulating/decapsulating the concatenation of the two shared secrets as per https://www.ietf.org/archive/id/draft-kwiatkowski-tls-ecdhe-mlkem-02.html#name-x25519mlkem768

If there are not sufficient generic EVP API calls available to do this in a truly generic way, focus on algorithms requiring no parameters for management and operation (x25519, x448, PQ KEMs) as well as EC-P algorithms. Ultimate goal is the instantiation of X25519MLKEM768 and P256MLKEM768 hybrids, but for test purposes, instantiation of an artificial X25519X448 hybrid KEM may also be possible/used for test purposes.

Note: This is a compile time concept, not run time selectable

**Comment by nhorman** [comment]
That may be sufficient, though I would think it would also want some discussion surrounding what sort of EVP_PKEY operations will and will not work with a hybrid key.   Examples can be found in our docs directory

**Comment by baentsch** [comment]
> That may be sufficient, though I would think it would also want some discussion surrounding what sort of EVP_PKEY operations will and will not work with a hybrid key. Examples can be found in our docs directory

The simple answer is "all operations that are required to make TLS1.3 KEM work" -- which admittedly is a set I don't know/cannot specify. My proposal is to keep implementing KM+KEM functionality until it works. That's the approach taken when doing `oqsprovider`. Not exactly scientific, but proven to work. And this time one can look into `oqsprovider` to get an idea how much needs to be done.
