### ISSUE TITLE
Update NEWS.md for 3.2 to elaborate on the release

### ISSUE THREAD

**Issue by arapov** [openssl/project#256]
- what's new?
  - check changes.md/news.md to identify something to highlight, that needs to be more verbose 
  - provide helpful links 
- ~~list known issues~~

**Comment by hlandau** [comment]
We discussed this at standup today and concluded we should change the format we use for NEWS.md going forward instead. NEWS.md can now contain slightly more elaboration and include links to documentation for now features. The basic template for a feature release's NEWS.md entry should in general be expected to match the announcement blogpost fairly closely and the 3.2a1 blogpost is a good starting point.

This issue is now about making the necessary changes for 3.2.

**Comment by hlandau** [comment]
https://github.com/openssl/openssl/pull/22774
