### ISSUE TITLE
p and q have lengths equal to half the modulus length

### ISSUE THREAD

**Issue by paulidale** [openssl/project#311]
Might need to add a verification step that confirms this.

Conditional on FIPS parameter.

Section A.1.2

**Comment by slontis** [comment]
I think this is related to FFC parameters? Not RSA?

**Comment by t8m** [comment]
I do not think there is any issue here. IMO this comes from section 5.1 RSA Key Pair Generation. "This standard specifies the use of a modulus whose bit length is an even integer and greater than or equal to 2048 bits. Furthermore, this standard specifies that p and q be of the same bit length – namely, half the bit length of n." That is inherent by the key generation algorithm specified which AFAIK did not change since 186-4.

**Comment by slontis** [comment]
As long as we conform to "A.1.5 Generation of Probable Primes with Conditions Based on Auxiliary
Provable Primes" there is no issue here..
We could update the code to reference FIPS 186-5 instead of FIPS186-4.
