### ISSUE TITLE
Ticket to run fuzzer early, Update feature planning.

### ISSUE THREAD

**Issue by hlandau** [openssl/project#352]
Revision to release checklists in future:

  - Fuzzing needs to start earlier
  - We need to decide how to handle Coverity better
  - Do we need to tie down CI OS targets (ubuntu-latest etc.)?
  - The last 2 weeks before release should be considered special

**Comment by arapov** [comment]
* When we plan a feature, we should identify whether it needs a fuzzer, and if it needs one, we need to write it.
* We want to run Coverity internally on our instance and cover more branches. Better Control of the updates. (https://github.com/openssl/private/issues/148)
* CI OS target is relevant to the bullet above (coverity). It is good idea to use latest release version instead of -latest.

@arapov will create a ticket and a template ticket to ensure we run the fuzzer early.

**Comment by arapov** [comment]
dupe fo #397
