### ISSUE TITLE
web page version of "man openssl-req" has broken formatting

### ISSUE THREAD

**Issue by jamuir** [openssl/project#394]
Text formatting breaks in the section describing the option `-subj`, and it remains broken on the rest of the webpage.

https://www.openssl.org/docs/manmaster/man1/openssl-req.html

Screenshot:

![openssl-req_20231219_122246](https://github.com/openssl/project/assets/5332385/a9246ddb-99ff-496d-a93e-0dbf0a4ccb5e)

**Comment by jamuir** [comment]
There is a similar problem with the webpage version of `man 5 config`:

https://www.openssl.org/docs/manmaster/man5/config.html

![config-20231219_164219](https://github.com/openssl/project/assets/5332385/b8b3522d-009a-49da-ac94-72ae1cdfceec)

**Comment by jamuir** [comment]
@levitte: any idea what is causing this?

**Comment by levitte** [comment]
Yes.  In the first case, there's a single backslash.  In the second case, there are dollar signs.

Because we wrap the documentation HTML in markdown when building our web site, those characters are interpreted by markdown, the backslash as an escape, the dollar as a math delimiter.

We have a fixup script for cases like this, where we're adding remedies for these things.  https://github.com/openssl/web/blob/master/bin/fix-man-html

**Comment by levitte** [comment]
I have a fix for those, currently testing
