### ISSUE TITLE
Address Clusterfuzz Timeout · decoder

### ISSUE THREAD

**Issue by nhorman** [openssl/project#800]
https://oss-fuzz.com/testcase-detail/4713086060658688

**Comment by Sashan** [comment]
Not much information to share yet. I've just extracted the reproducer into simple `.c` program so I can poke around in more convenient way. This is what I know about key which comes from fuzzer::
```
EVP_PKEY_get_bits(pkey): 16
EVP_PKEY_get_security_bits(pkey): 8
EVP_PKEY_get0_type_name(): RSA
EVP_PKEY_get0_description(): OpenSSL RSA implementation
```
What's interesting the bits and security bits are well below the check we do in fuzzer code here:
```
       /* Private and pairwise checks are unbounded, skip for large keys. */
        if (EVP_PKEY_get_bits(pkey) <= 16384) {
            EVP_PKEY_private_check(ctx);
            EVP_PKEY_pairwise_check(ctx);
        }
```
The execution time of `EVP_PKEY_pairwise_checks()` exceeds the 45sec timeout set by fuzzer. The reproducer execution time on my notebook (ryzen7) takes roughly one minute and forty secs.

I'll keep looking to find out what's going on there.


[reproducer.69134.tgz](https://github.com/user-attachments/files/16590236/reproducer.69134.tgz)

**Comment by Sashan** [comment]
The `RSA` key as decoded has those properties:
```
(gdb) call BN_num_bits(rsa->n)
$36 = 16
(gdb) call BN_num_bits(rsa->e)
$37 = 11
(gdb) call BN_num_bits(rsa->d)
$38 = 0
(gdb) call BN_num_bits(rsa->p)
$39 = 16365
(gdb) call BN_num_bits(rsa->q)
$40 = 14
```
The `EVP_PKEY_get_bits(pkey): 16` mention in earlier comment comes from `EVP_PKEY::cache` member.
the cache is initialized `evp_keymgmt_util_cache_keyinfo()` function. Member bits matches `rsa::n`.

Similar `EVP_PKEY_get_security_bits()` retreives `security_bits` member which is derived from `rsa::n`
by `ossl_ifc_ffc_compute_security_bits()`:
```
(gdb) call ossl_ifc_ffc_compute_security_bits(16)
$41 = 8
```

According to what @t8m suggests we can refuse the key because `BN_num_bits(rsa-p) > BN_num_bits(rsa->n)`.

quoting @t8m 
```
to generalize the check - any value on import (p, q, factors, all CRT params, d, e) must have at most the same number of bits as n.
```

the `n` represents public modulus for particular key. If any parameter `e`, `d`, `p` or `q` is longer (in number of bits) then public modulus, then key is invalid. Such parameter does not fit to space provided by `n`. That's my sort of vague understanding.

**Comment by Sashan** [comment]
Pull request got submitted https://github.com/openssl/openssl/pull/25190
