### ISSUE TITLE
Webinar for october - certificate manipulation

### ISSUE THREAD

**Issue by nhorman** [openssl/project#852]

**Comment by vavroch2010** [comment]
@vdukhovni please share link here

**Comment by Sashan** [comment]
I think this is the link, just in case anyone wants to jump to review vagon:
https://docs.google.com/presentation/d/1xU2-U_6uUW4gB3j_v7EQC81t1RZ_slHyY_91MLlMDEg/edit#slide=id.g2b4be0ee06d_0_0

**Comment by baentsch** [comment]
Hmm -- I just opened it and this is what I saw: 
![image](https://github.com/user-attachments/assets/5317e6ee-b8d4-4654-82fb-c54fbdf8c466)

Is my screen setup so strange or should the word "SSL" indeed be pretty much invisible?

**Comment by baentsch** [comment]
After quickly going through the slides, allow me to state that it is a very good run through "everything certificate" with lots of pointers for further reading (up on commands) as well as concrete usage(s) of the openssl apps. What I'm less sure about is that this can be given in one webinar: This is 49 pages and my rule of thumb is 3mins per slide -- so unless the webinar goes for 3 hours (?) what about the suggestion to split this deck in two: One set of slides that gets shown and one set of slides marked "homework" for the interested? Alternative: Do 2-3 webinars. Otherwise, I'm afraid this is too much material for the uninitiated and you risk "losing" them/their attention -- and I think "uninitiated" is an apt description of most of the audience, right?

**Comment by baentsch** [comment]
Oops -- tagging @vdukhovni just to be sure...

**Comment by vavroch2010** [comment]
After reviewing the webinar, I found that there is an opportunity to enhance the audience's understanding by providing more transparent explanations. The current amount of information could be spread over two or three sessions to allow for more in-depth explanations. It would prevent the audience from feeling overwhelmed and ensure they are fully informed about the topic. 
It is not consistent from a graphic point of view. Sometimes, some parameters are bold - why? Many slides have too much text.
I see it as an extensive list of commands that need further explanation of why it is done this way or what other options there are.
And as @baentsch mentioned, we will quickly lose an audience, which is unwanted.

**Comment by baentsch** [comment]
Checking again triggered by @vavroch2010 's comments, allow me to say that the logo problem mentioned above is resolved and that the contents do seem streamlined, so Thanks for that @vdukhovni ! There's still a lot of material, though. Even speaking fast as you stated to do, Victor, I personally still believe there is room for splitting out material for a second or third webinar to make the topic area more fully "digestable". For example, "EKU" could be explained more deeply together with other certificate extensions (also being discussed in the context of PQC with [composite signatures](https://datatracker.ietf.org/doc/draft-ietf-lamps-pq-composite-sigs/) for example -- where I don't grasp all details as to what is permissible or doable as per RFC and/or OpenSSL APIs).

But then again, who knows how many people are interested in such details?

So what about this idea: Move some slides to an appendix you wouldn't need to show if time were running out -- but asking (maybe adding a bullet point for the question) whether there's interest for a further "deep dive"/next webinar on contents in this appendix, e.g., cert extensions (or anything else cert related that the audience may voice interest in during the webinar)?
