### ISSUE TITLE
QUIC: Endpoints MUST treat the receipt of a TLS KeyUpdate message as a connection error of type 0x010a, equivalent to a fatal TLS alert of unexpected_message; see Section 4.8.

### ISSUE THREAD

**Issue by nhorman** [openssl/project#899]
This is a missing MUST item from the spreadsheet here:
https://docs.google.com/spreadsheets/d/1is0eRNrmNwzqcCTmTPYJwC3fswpYpqmY87-5CylraLc/edit?gid=1067533579#gid=1067533579

Need to determine if this is still missing, and if it is, correct it

Investigate and if work required create another issue with description what needs to be done

**Comment by nhorman** [comment]
Can confirm that initiating a key update in QUIC does not produce a key update TLS record, as SSL_key_update has a special case for QUIC, in which generates a TXKU packet in a quic datagram in accordance with https://datatracker.ietf.org/doc/html/rfc9001#name-key-update

On receive there is still work to be done I believe, in that the receipt of a Key update TLS record would still be processed by tls_process_key_update().

I believe that the work needed here is that ch_on_crypto_recv_record should interrogate the buffer received from ossl_quic_rstream_get_record , to see if it is a TLS key update message, and if so, it should immediately call ossl_quic_channel_raise_protocol_error citing error 0x010a as per RFC 9001 and return 0, ensuring that we close the connection on receipt of a Key Update message

Still need to figure out how to test such a condition, as we never send a Key Update message

**Comment by mattcaswell** [comment]
> On receive there is still work to be done I believe, in that the receipt of a Key update TLS record would still be processed by tls_process_key_update().
> 
> I believe that the work needed here is that ch_on_crypto_recv_record should interrogate the buffer received from ossl_quic_rstream_get_record , to see if it is a TLS key update message, and if so, it should immediately call ossl_quic_channel_raise_protocol_error citing error 0x010a as per RFC 9001 and return 0, ensuring that we close the connection on receipt of a Key Update message
> 
> Still need to figure out how to test such a condition, as we never send a Key Update message

IMO we are already correctly handling the receipt of a KeyUpdate message.

On receipt of a new handshake message the TLS state machine calls the relevant "transition" function to determine whether it is valid to receive that message in this context.

On the server side the relevant "transition" code for KeyUpdate is here:

https://github.com/openssl/openssl/blob/5eb9453cee50e28e5acb9c12bb26394dd31c04ad/ssl/statem/statem_srvr.c#L163-L166

On the client side it is here:

https://github.com/openssl/openssl/blob/5eb9453cee50e28e5acb9c12bb26394dd31c04ad/ssl/statem/statem_clnt.c#L189-L192

In both cases we only return 1 from the transition function on receipt of a KeyUpdate message if we're not doing QUIC. Otherwise we will return 0. A return of 0 from the transition function causes the TLS state machine to attempt to send an "unexpected_message" alert.

Ultimately that will cause the QUIC `ch_on_handshake_alert` callback to be called which does this:

https://github.com/openssl/openssl/blob/5eb9453cee50e28e5acb9c12bb26394dd31c04ad/ssl/quic/quic_channel.c#L1098-L1101

i.e. it raises a QUIC protocol error with error code `OSSL_QUIC_ERR_CRYPTO_ERR_BEGIN + alert_code`. Here `OSSL_QUIC_ERR_CRYPTO_ERR_BEGIN` has the value 0x100, and alert_code is 0x0a (unexpected_message), i.e. the QUIC protocol error is 0x10a as required.

**Comment by Sashan** [comment]
filed ticket which asks test to be added https://github.com/openssl/project/issues/923

**Comment by mattcaswell** [comment]
> filed ticket which asks test to be added https://github.com/openssl/project/issues/923

A test for this already exists. Further details noted in the comments in #923.

Can we just close this issue?

**Comment by t8m** [comment]
Yes, closing
